src/Entity/Product.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

define('DAYS_IN_YEAR', 365);

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product {
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $name;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Prices", mappedBy="product", fetch="EAGER")
	 */
	private $prices;

	/**
	 * @ORM\Column(type="text")
	 */
	private $specialDates;

	public function __construct() {
		$this->prices       = new ArrayCollection();
		$this->specialDates = new ArrayCollection();
	}

	public function getId() {
		return $this->id;
	}

	public function getName(): ?string {
		return $this->name;
	}

	public function setName(string $name): self {
		$this->name = $name;

		return $this;
	}

	/**
	 * @return Collection|Prices[]
	 */
	public function getPrices(): Collection {
		return $this->prices;
	}

	/**
	 * @return Collection|Prices[]
	 */
	public function getDefaultPrice() {
		foreach ($this->prices as $price) {
			if ($price->getIsDefault()) {
				return $price;
			}
		}
	}

	public function addPrice(Prices $price): self {
		if ( ! $this->prices->contains($price)) {
			$this->prices[] = $price;
			$price->setProduct($this);
		}

		return $this;
	}

	public function removePrice(Prices $price): self {
		if ($this->prices->contains($price)) {
			$this->prices->removeElement($price);
			// set the owning side to null (unless already changed)
			if ($price->getProduct() === $this) {
				$price->setProduct(null);
			}
		}

		return $this;
	}

	public function getSpecialDates() {
		$dates = array();
		$today = strtotime(date('d.m.Y'));
		if ($this->specialDates) {
			$spDates = unserialize($this->specialDates);
			foreach ($spDates as $key => $special_date) {
				$date = strtotime($special_date);
				if ($date >= $today) {
					$dates[] = $special_date;
				}
			}
		}

		return $dates;
	}

	public function setSpecialDates(array $dates): self {
		$this->specialDates = serialize($dates);

		return $this;
	}
}

templates/index/index.html.twig
{% extends 'base.html.twig' %}


{% block header %}
    <div class="topline center-align">
        <h1>{{ h1 }}</h1>
        {% block info %}
            <div class="container">
                <h5>Change prices, update prices, view prices!</h5>
                <p>Click on Product Row to see All Set Prices</p>
                <blockquote class="left-align">
                    By default, price for today is special price with smaller interval if it set.
                </blockquote>
            </div>
        {% endblock %}
    </div>
{% endblock %}

{% block body %}
    <div class="row">
        {% block main %}
            <div class="col s12">
                <h5 class="header">Available products</h5>
                <div class="collection">
                    {% for product in products %}
                        <a href="/product/{{ product.id }}" class="collection-item">{{ product.name }}
                            <span class="badge">default price: ${{ product.defaultPrice }}</span>
                            {% if product.actualPrice %}
                            <span class="badge new today"> ${{ product.actualPrice }}</span>
                            {% endif %}
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% endblock %}
    </div>
{% endblock %}