src/Entity/Prices.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PricesRepository")
 */
class Prices {
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\ManyToOne(targetEntity="App\Entity\Product", inversedBy="prices", fetch="EAGER")
	 * @ORM\JoinColumn(name="product_id", referencedColumnName="id")
	 */
	private $product;

	/**
	 * @ORM\Column(type="float")
	 */
	private $value;

	/**
	 * @ORM\Column(type="boolean")
	 */
	private $is_default;

	/**
	 * @ORM\Column(type="datetime",options={"default":"CURRENT_TIMESTAMP"})
	 */
	private $date_from;

	/**
	 * @ORM\Column(type="datetime",options={"default":"CURRENT_TIMESTAMP"})
	 */
	private $date_to;

	/**
	 * @ORM\Column(type="datetime",options={"default":"CURRENT_TIMESTAMP"})
	 */
	private $updated;

	public function getId() {
		return $this->id;
	}

	public function getProduct(): ?Product {
		return $this->product;
	}

	public function setProduct(?Product $product): self {
		$this->product = $product;

		return $this;
	}

	public function getValue(): ?float {
		return $this->value;
	}

	public function setValue(float $value): self {
		$this->value = $value;

		return $this;
	}

	public function getIsDefault(): ?bool {
		return $this->is_default;
	}

	public function setIsDefault(bool $is_default): self {
		$this->is_default = $is_default;

		return $this;
	}

	public function getDateFrom(): ?\DateTimeInterface {
		return $this->date_from;
	}

	public function setDateFrom(\DateTimeInterface $date_from): self {
		$this->date_from = $date_from;

		return $this;
	}

	public function getDateTo(): ?\DateTimeInterface {
		return $this->date_to;
	}

	public function setDateTo(\DateTimeInterface $date_to): self {
		$this->date_to = $date_to;

		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getUpdated() {
		return $this->updated;
	}

	/**
	 * @param mixed $updated
	 */
	public function setUpdated($updated): void {
		$this->updated = $updated;
	}

	public function getDateInterval() {
		if ( ! $this->is_default) {
			return $this->date_to->diff($this->date_from);
		} else {
			// set big date interval for default prices
			return new \DateInterval('P99999Y');
		}

	}
}

src/Entity/Product.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

define('DAYS_IN_YEAR', 365);

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product {
	/**
	 * @ORM\Id()
	 * @ORM\GeneratedValue()
	 * @ORM\Column(type="integer")
	 */
	private $id;

	/**
	 * @ORM\Column(type="string", length=255)
	 */
	private $name;

	/**
	 * @ORM\OneToMany(targetEntity="App\Entity\Prices", mappedBy="product", fetch="EAGER")
	 */
	private $prices;

	/**
	 * @ORM\Column(type="text")
	 */
	private $specialDates;

	public function __construct() {
		$this->prices       = new ArrayCollection();
		$this->specialDates = new ArrayCollection();
	}

	public function getId() {
		return $this->id;
	}

	public function getName(): ?string {
		return $this->name;
	}

	public function setName(string $name): self {
		$this->name = $name;

		return $this;
	}

	/**
	 * @return Collection|Prices[]
	 */
	public function getPrices(): Collection {
		return $this->prices;
	}

	/**
	 * @return Collection|Prices[]
	 */
	public function getDefaultPrice() {
		foreach ($this->prices as $price) {
			if ($price->getIsDefault()) {
				return $price;
			}
		}
	}

	public function addPrice(Prices $price): self {
		if ( ! $this->prices->contains($price)) {
			$this->prices[] = $price;
			$price->setProduct($this);
		}

		return $this;
	}

	public function removePrice(Prices $price): self {
		if ($this->prices->contains($price)) {
			$this->prices->removeElement($price);
			// set the owning side to null (unless already changed)
			if ($price->getProduct() === $this) {
				$price->setProduct(null);
			}
		}

		return $this;
	}

	public function getSpecialDates() {
		$dates = array();
		$today = strtotime(date('d.m.Y'));
		if ($this->specialDates) {
			$spDates = unserialize($this->specialDates);
			foreach ($spDates as $key => $special_date) {
				$date = strtotime($special_date);
				if ($date >= $today) {
					$dates[] = $special_date;
				}
			}
		}

		return $dates;
	}

	public function setSpecialDates(array $dates): self {
		$this->specialDates = serialize($dates);

		return $this;
	}
}

src/Controller/ProductController.php
<?php
/**
 * Created by PhpStorm.
 * User: kathy
 * Date: 07.07.18
 * Time: 11:10
 */

namespace App\Controller;

use App\Entity\Prices;
use App\Entity\Product;
use App\Service\ProductPricesManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProductController extends AbstractController {

	/**
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function index() {

		$products         = array();
		$productObjects   = $this->getDoctrine()->getRepository(Product::class)->findAll();
		$pricesRepository = $this->getDoctrine()->getRepository(Prices::class);
		$productManager   = new ProductPricesManager();

		foreach ($productObjects as $pObj) {
			$criteria    = $productManager->getSortCriteria($pObj->getSpecialDates());
			$prices      = $productManager->getSortedPrices($pricesRepository->findTodaysActualPrices($pObj->getId()), $criteria);
			$actualPrice = $prices ? reset($prices)->getValue() : false;

			$products[] = array(
				'id'           => $pObj->getId(),
				'name'         => ucfirst($pObj->getName()),
				'defaultPrice' => $pObj->getDefaultPrice()->getValue(),
				'actualPrice'  => $actualPrice,
				'prices'       => $productManager->buildPricesArray($prices)
			);
		}

		return $this->render('index/index.html.twig', array(
			'h1'       => 'Welcome to Prices Manager!',
			'products' => $products
		));
	}


	/**
	 * /product/{id}
	 *
	 * @param $id
	 *
	 * @return \Symfony\Component\HttpFoundation\Response
	 */
	public function show($id) {
		$productRepository = $this->getDoctrine()->getRepository(Product::class);
		$productManager    = new ProductPricesManager();

		$product = $productRepository->find($id);

		return $this->render('product/product_details.html.twig', array(
			'h1'      => ucfirst($product->getName()),
			'product' => array(
				'id'           => $product->getId(),
				'defaultPrice' => $product->getDefaultPrice()->getValue(),
				'prices'       => $productManager->buildPricesArray($product->getPrices()->getValues()),
				'specialDates' => $product->getSpecialDates()
			)
		));
	}
}

templates/product/product_details.html.twig
{% extends 'index/index.html.twig' %}

{% block stylesheets %}
    <link rel="stylesheet" href="{{ asset('css/air-datepicker/datepicker.min.css') }}">
{% endblock %}

{% block info %}
    <div><a class="waves-effect waves-light btn" href="/">Go Back</a></div>
    <div class="container">
        <h6>Set special sort by clicking near:</h6>
        <form class="form inline" method="post" action="/api">
            <input type="text" name="specDates" id="multidatepicker" data-multiple-dates-separator=", "
            value="{% for date in product.specialDates %}{{ date }}, {% endfor %}"
            />
            <input type="hidden" name="productId" value="{{ product.id }}"/>
            <input type="hidden" name="action" value="setDates"/>
            <button class="btn green">Ok</button>
        </form>
        <p>Special Sort description: Use price which was set later</p>
    </div>

{% endblock %}

{% block main %}
    <div class="col s12">
        <h5 class="header">Actual special prices</h5>
        <a href="#" class="waves-effect waves-light btn" id="addRow">add price</a>
        <table class="table responsive-table highlight" id="editable-table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Special Price, $</th>
                <th>From</th>
                <th>To</th>
                <th>Mark</th>
            </tr>
            </thead>
            <tbody>
                {% for price in product.prices %}
                    <tr>
                        <td>{{ product.id }}-{{ price.id }}</td>
                        <td>{{ price.value }}</td>
                        <td>{{ price.dateFrom }}</td>
                        <td>{{ price.dateTo }}</td>
                        <td>
                            {% if price.default %}
                                <span class="badge blue white-text">default</span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block javascripts %}
    <script src="{{ asset('js/jquery.tabledit.min.js') }}"></script>
    <script src="{{ asset('js/air-datepicker/datepicker.min.js') }}"></script>
    <script src="{{ asset('build/js/app.js') }}"></script>
{% endblock %}